# Generated by Django 2.2.3 on 2020-01-28 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PortalModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('nickname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('datafile', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=200)),
                ('datatype', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
