# Generated by Django 2.2.3 on 2020-02-18 19:08

import PortalModel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalModel', '0002_auto_20200128_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='datafile',
            field=models.FileField(upload_to=PortalModel.models.user_directory_path),
        ),
    ]
