# Generated by Django 2.2.3 on 2020-02-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalModel', '0004_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.CharField(default='', max_length=700),
        ),
    ]
