# Generated by Django 2.2.3 on 2020-02-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalModel', '0005_auto_20200220_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
